<?php

namespace ContainerRMI7bDE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OGJQrcPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OGJQrcP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OGJQrcP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\MicroPostController::index' => ['privates', '.service_locator.69Raho3.App\\Controller\\MicroPostController::index()', 'getMicroPostControllerindexService', true],
            'App\\Controller\\MicroPostController::showOne' => ['privates', '.service_locator.g2QUtQW.App\\Controller\\MicroPostController::showOne()', 'getMicroPostControllershowOneService', true],
            'App\\Controller\\MicroPostController::add' => ['privates', '.service_locator.69Raho3.App\\Controller\\MicroPostController::add()', 'getMicroPostControlleraddService', true],
            'App\\Controller\\MicroPostController::edit' => ['privates', '.service_locator.G6JJNc7.App\\Controller\\MicroPostController::edit()', 'getMicroPostControllereditService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\MicroPostController:index' => ['privates', '.service_locator.69Raho3.App\\Controller\\MicroPostController::index()', 'getMicroPostControllerindexService', true],
            'App\\Controller\\MicroPostController:showOne' => ['privates', '.service_locator.g2QUtQW.App\\Controller\\MicroPostController::showOne()', 'getMicroPostControllershowOneService', true],
            'App\\Controller\\MicroPostController:add' => ['privates', '.service_locator.69Raho3.App\\Controller\\MicroPostController::add()', 'getMicroPostControlleraddService', true],
            'App\\Controller\\MicroPostController:edit' => ['privates', '.service_locator.G6JJNc7.App\\Controller\\MicroPostController::edit()', 'getMicroPostControllereditService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\MicroPostController::index' => '?',
            'App\\Controller\\MicroPostController::showOne' => '?',
            'App\\Controller\\MicroPostController::add' => '?',
            'App\\Controller\\MicroPostController::edit' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\MicroPostController:index' => '?',
            'App\\Controller\\MicroPostController:showOne' => '?',
            'App\\Controller\\MicroPostController:add' => '?',
            'App\\Controller\\MicroPostController:edit' => '?',
        ]);
    }
}
