<?php

namespace ContainerRMI7bDE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMicroPostService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\MicroPost' shared autowired service.
     *
     * @return \App\Entity\MicroPost
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/MicroPost.php';

        return $container->privates['App\\Entity\\MicroPost'] = new \App\Entity\MicroPost();
    }
}
