<?php

namespace ContainerRMI7bDE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMicroPostControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.69Raho3.App\Controller\MicroPostController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.69Raho3.App\\Controller\\MicroPostController::index()'] = ($container->privates['.service_locator.69Raho3'] ?? $container->load('get_ServiceLocator_69Raho3Service'))->withContext('App\\Controller\\MicroPostController::index()', $container);
    }
}
