<?php

namespace ContainerRMI7bDE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMicroPostControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G6JJNc7.App\Controller\MicroPostController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G6JJNc7.App\\Controller\\MicroPostController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'post' => ['privates', 'App\\Entity\\MicroPost', 'getMicroPostService', true],
            'posts' => ['privates', 'App\\Repository\\MicroPostRepository', 'getMicroPostRepositoryService', true],
        ], [
            'post' => 'App\\Entity\\MicroPost',
            'posts' => 'App\\Repository\\MicroPostRepository',
        ]))->withContext('App\\Controller\\MicroPostController::edit()', $container);
    }
}
