<?php

namespace ContainerP2VuVWX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMicroPostControlleraddCommentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dkUws00.App\Controller\MicroPostController::addComment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dkUws00.App\\Controller\\MicroPostController::addComment()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'post' => ['privates', 'App\\Entity\\MicroPost', 'getMicroPostService', true],
            'comments' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
        ], [
            'post' => 'App\\Entity\\MicroPost',
            'comments' => 'App\\Repository\\CommentRepository',
        ]))->withContext('App\\Controller\\MicroPostController::addComment()', $container);
    }
}
