<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMMcqiDS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMMcqiDS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMMcqiDS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMMcqiDS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMMcqiDS\App_KernelDevDebugContainer([
    'container.build_hash' => 'MMcqiDS',
    'container.build_id' => '7523f444',
    'container.build_time' => 1757258040,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMMcqiDS');
