<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSNcApK5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSNcApK5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSNcApK5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSNcApK5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSNcApK5\App_KernelDevDebugContainer([
    'container.build_hash' => 'SNcApK5',
    'container.build_id' => '05d6afc9',
    'container.build_time' => 1757235823,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSNcApK5');
