<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHjjTSvA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHjjTSvA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHjjTSvA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHjjTSvA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHjjTSvA\App_KernelDevDebugContainer([
    'container.build_hash' => 'HjjTSvA',
    'container.build_id' => '1533e001',
    'container.build_time' => 1757187889,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHjjTSvA');
